### PR TITLE
Drop support for Puppet 4, 5, 6 (EOL)

### PR DESCRIPTION
**Pull request by smortex**
Also include:

* #98
* #99
* #100

### CODE REVIEW

**Comment by smortex** [comment]
Interesting, in facterdb, Archlinux (and a bunch of other OS) does not have a `puppetversion` fact.

**Review by kenyon — APPROVED** [review]

**Comment by jhoblitt** [comment]
I'd rather the individual PRs aggregated here are merged separately so they appear in the change-log.

**Comment by kenyon** [comment]
@jhoblitt they'll all appear in the changelog when closed, regardless of how they are merged.

**Review by jhoblitt — CHANGES_REQUESTED** [review]
There is a lot going on this PR that I feel would be better merged as isolated PRs that appear in the changelog.  Also, some of the commits in this branch have a lot going on in them that isn't reflected in the commit messages. E.g. https://github.com/voxpupuli/puppet-augeas/pull/101/commits/f6974ed953fef63dfad74f6e0be3723266176867

The PR title here also won't be very helpful in the changelog.  What versions of puppet is support being dropped for?

I suggest starting with a small PR that only removes the EOL puppet versions.

**Comment by jhoblitt** [comment]
> @jhoblitt they'll all appear in the changelog when closed, regardless of how they are merged.

Closed but unmerged PRs do not appear in the changelog.

**Comment by kenyon** [comment]
> > @jhoblitt they'll all appear in the changelog when closed, regardless of how they are merged.
> 
> Closed but unmerged PRs do not appear in the changelog.

When this PR is merged, the included ones will also be closed as merged.

**Comment by kenyon** [comment]
> There is a lot going on this PR that I feel would be better merged as isolated PRs that appear in the changelog. Also, some of the commits in this branch have a lot going on in them that isn't reflected in the commit messages. E.g. [f6974ed](https://github.com/voxpupuli/puppet-augeas/commit/f6974ed953fef63dfad74f6e0be3723266176867)

AFAICT, in that commit, all of the deleted code was only applicable to EOL versions of Puppet, where Augeas was not included in the all-in-one packages like we have now.

**Comment by smortex** [comment]
> The PR title here also won't be very helpful in the changelog. What versions of puppet is support being dropped for?

:+1: Fixed, thanks!



> When this PR is merged, the included ones will also be closed as merged.

That's correct, when all commits in a PR are merged, the PR is marked as merged and GitHub ChangeLog Generator include it as expected.

> AFAICT, in that commit, all of the deleted code was only applicable to EOL versions of Puppet, where Augeas was not included in the all-in-one packages like we have now.

Correct, and we also discover that the legacy code was used on some platforms because they do not ship with `puppetversion`?!

**Review by jhoblitt — APPROVED** [review]

**Comment by jhoblitt** [comment]
Could we either accept the arch failure and merge this or remove arch from this PR? We need to get a forge release out.

**Comment by smortex** [comment]
> Could we either accept the arch failure and merge this or remove arch from this PR? We need to get a forge release out.

@bastelfreak you are my Arch referent :-D  What do you think we should do?

**Comment by bastelfreak** [comment]
The Arch Linux failure was an actual bug. the puppet package didn't depend on ruby-augeas. I fixed the package upstream.

**Pull request merged**
