### PR TITLE
release 2.0.0

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Review by kenyon — APPROVED** [review]
The reference docs could use some formatting improvements, and we need to remove those old OSes from the metadata, but we can do those things later.

**Comment by jhoblitt** [comment]
Ugh. I thought the metadata.json was already cleaned up.

**Comment by smortex** [comment]
> Ugh. I thought the metadata.json was already cleaned up.

As this is a major version, I suggest dropping EOL systems before releasing.
We can probably also move the old `CHANGELOG.md` to `HISTORY.md` and adjust it's style so that GCG only add entries from GitHub PR for new changes.

**Comment by jhoblitt** [comment]
I agree. metadata.json needs to be cleaned up before a  major release.

**Comment by jhoblitt** [comment]
The changelog has been regenerated after the merge of:
- #104 
- #105 
- #106 
- #107 
- #108 
- #109

**Review by kenyon — APPROVED** [review]

**Pull request merged**
